# Generated by Django 4.1.7 on 2023-03-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letterContent', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/')),
                ('packageType', models.CharField(choices=[('urna', 'Urna'), ('regalo', 'Regalo'), ('caja', 'Caja'), ('caja fuerte', 'Caja Fuerte')], default='caja', max_length=50)),
                ('finalDestination', models.CharField(choices=[('enterrar', 'Enterrar'), ('quemar', 'Quemar'), ('guardar', 'Guardar'), ('regalar', 'Regalar')], default='enterrar', max_length=50)),
                ('recipientName', models.CharField(max_length=250)),
                ('recipientAddress', models.CharField(max_length=250)),
                ('recipientPhone', models.CharField(max_length=250)),
                ('clientName', models.CharField(max_length=250)),
                ('clientAddress', models.CharField(max_length=250)),
                ('clientPhone', models.CharField(max_length=250)),
                ('clientEmail', models.CharField(max_length=250)),
                ('paymentMethod', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('paypal', 'Paypal'), ('pagomovil', 'Pago Movil')], default='transferencia', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dimensions', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Detective',
        ),
    ]
