# Generated by Django 4.1.7 on 2023-03-11 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_boxdata_delete_detective'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxdata',
            old_name='images',
            new_name='image',
        ),
    ]
