# Generated by Django 4.1.7 on 2023-03-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='icon',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
