# Generated by Django 4.1.7 on 2023-03-11 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_destinations_packages_alter_boxdata_finaldestination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='boxdata',
            name='packageType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageType', to='api.packages'),
        ),
    ]
