# Generated by Django 4.1.7 on 2023-03-11 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_boxdata_id_alter_boxdata_packagetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='boxdata',
            name='packageType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.packages'),
        ),
    ]
