# Generated by Django 4.1.7 on 2023-03-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_boxdata_confirmationnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxdata',
            name='paymentMethod',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('zelle', 'Paypal'), ('pagomovil', 'Pago Movil')], default='transferencia', max_length=50),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='packages',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
