# Generated by Django 4.1.7 on 2023-03-12 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_boxdata_paymentmethod_alter_destinations_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxdata',
            name='image',
        ),
        migrations.AlterField(
            model_name='boxdata',
            name='packageType',
            field=models.CharField(choices=[('ataud', 'Ataud'), ('regalo', 'Regalo'), ('caja', 'Caja'), ('caja fuerte', 'Caja Fuerte')], default='caja', max_length=50),
        ),
        migrations.CreateModel(
            name='BoxDataImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('boxData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.boxdata')),
            ],
        ),
    ]
