# Generated by Django 4.1.7 on 2023-03-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_boxdata_id_alter_boxdata_packagetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxdata',
            name='finalDestination',
            field=models.CharField(choices=[('enterrar', 'Enterrar'), ('quemar', 'Quemar'), ('guardar', 'Guardar'), ('regalar', 'Regalar')], default='enterrar', max_length=50),
        ),
        migrations.AlterField(
            model_name='boxdata',
            name='packageType',
            field=models.CharField(choices=[('urna', 'Urna'), ('regalo', 'Regalo'), ('caja', 'Caja'), ('caja fuerte', 'Caja Fuerte')], default='caja', max_length=50),
        ),
    ]
