# Generated by Django 4.1.7 on 2023-03-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_boxdata_image_alter_boxdata_packagetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxdata',
            name='clientAddress',
        ),
    ]
