# Generated by Django 4.1.7 on 2023-03-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_boxdata_clientaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxdata',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='boxdata',
            name='recipientAddress',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='boxdata',
            name='recipientName',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='boxdata',
            name='recipientPhone',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
