# Generated by Django 4.1.7 on 2023-03-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_boxdata_total_alter_boxdata_recipientaddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='number_phone',
        ),
    ]
