# Generated by Django 4.1.7 on 2023-03-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_last_name_contact_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxdata',
            name='letterContent',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(),
        ),
    ]
